import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// https://docusaurus.io/docs/sidebar

const sidebars: SidebarsConfig = {
  introduction: [{ type: 'autogenerated', dirName: 'introduction' }],
  businessAnalysis: [{ type: 'autogenerated', dirName: '01-overview' }],
  requirements: [{ type: 'autogenerated', dirName: '02-requirements' }],
  external: [{ type: 'autogenerated', dirName: '03-external' }],
  internal: [{ type: 'autogenerated', dirName: '04-internal' }],
};

export default sidebars;
