name: Deploy to GitHub Pages
# 詳細は公式サイトを参照
# https://docs.github.com/ja/actions/writing-workflows/workflow-syntax-for-github-actions

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - name: '[1/6] checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: '[2/6] setup node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: '[3/6] setup pnpm'
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: '[4/6] install dependencies'
        run: pnpm install --frozen-lockfile

      - name: '[5/6] build'
        run: pnpm --filter @specment/docs build

      - name: '[6/6] upload Build Artifact'
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/docs/build

  deploy:
    name: deploy to GitHub Pages
    needs: build
    permissions:
      pages: write      # Pagesデプロイ用権限
      id-token: write   # OIDCトークン発行用権限
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}
