name: Release
# Automated release workflow for packages/specment npm publishing
# Integrates with changesets for version management and changelog generation

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release packages/specment
    runs-on: ubuntu-latest
    steps:
      - name: '[1/8] checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: '[2/8] setup node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: '[3/8] setup pnpm'
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: '[4/8] install dependencies'
        run: pnpm install --frozen-lockfile

      - name: '[5/8] build packages/specment'
        run: pnpm --filter @plenarc/specment build

      - name: '[6/8] create release pull request or publish to npm'
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm changeset publish
          title: 'chore: release packages'
          commit: 'chore: release packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: '[7/8] send slack notification on release'
        if: steps.changesets.outputs.published == 'true'
        run: |
          echo "Published packages:"
          echo "${{ steps.changesets.outputs.publishedPackages }}"
          # Add Slack notification here if needed

      - name: '[8/8] create GitHub release'
        if: steps.changesets.outputs.published == 'true'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}
          name: Release v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}
          body: |
            ## Changes
            
            See [CHANGELOG.md](https://github.com/plenarc/specment/blob/main/packages/specment/CHANGELOG.md) for details.
            
            ## Installation
            
            ```bash
            npm install -g @plenarc/specment
            ```
            
            ## Published Packages
            
            ${{ steps.changesets.outputs.publishedPackages }}
          draft: false
          prerelease: false